# Generated by Django 4.2.5 on 2024-02-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='flats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primarykey', models.IntegerField()),
                ('price', models.IntegerField()),
                ('bathroomnumber', models.IntegerField()),
                ('bedroomnumber', models.IntegerField()),
                ('gov', models.TextField()),
                ('city', models.TextField()),
                ('floornumber', models.IntegerField()),
                ('with_f', models.BooleanField()),
                ('active', models.BooleanField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='flat_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='flat_images/')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.flats')),
            ],
        ),
    ]
