# Generated by Django 4.2.5 on 2024-02-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flats',
            name='primarykey',
        ),
    ]
