# Generated by Django 4.2.5 on 2024-02-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_remove_flats_primarykey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admins_s',
        ),
    ]
