# Generated by Django 4.2.7 on 2024-02-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_flats_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nationalid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
