# Generated by Django 4.2.7 on 2024-02-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_users_nationalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downpayment', models.IntegerField()),
                ('bathroomnumber', models.IntegerField()),
                ('bedroomnumber', models.IntegerField()),
                ('detiels', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('mainimage', models.ImageField(null=True, upload_to='social_house_mainimg/')),
            ],
        ),
        migrations.CreateModel(
            name='socialhouse_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='social_house_imgs/')),
                ('social_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.social_house')),
            ],
        ),
    ]
