# Generated by Django 4.2.7 on 2024-03-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_social_house_socialhouse_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_house',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
